### PR TITLE
Improve query string handling in Python output

### PR DESCRIPTION
**Pull request by verhovsky**
The new tests in the PR should explain what I'm trying to accomplish here

- detect when a query string cannot be losslessly converted to a list of tuples/dict
- preserve ordering of arguments
- unify the code that parses query strings in --data and the URL

I still need to update the existing tests and clean up the code.

### CODE REVIEW

**Comment by NickCarneiro** [comment]
Dicts don't allow duplicate keys though. I believe there is a test that checks for this.

**Comment by verhovsky** [comment]
I thought that too, but curlconverter converts those to a list for one param name, not multiple entries in the list of params:

```sh
curl 'https://example.com/?firstparam=1&secondparam=2&firstparam=1'
```

is converted to

```py
# [...]
params = (
    ('firstparam', ['1', '1']),
    ('secondparam', '2'),
)
# [...]
```

I wonder if that's what the comment "It seems impossible to parse and reproduce query strings 100% accurately" is about... it might be best if this situation was detected, and in that case you output a tuple of tuples in the correct order (might need to do the URL parsing with a different library), but a dictionary otherwise.

**Comment by NickCarneiro** [comment]
Ah, you've discovered a pretty big inconsistency.

Curlconverter respects duplicate keys for POST but not GET.

curl -X POST 'https://example.com/' --data firstparam=1&secondparam=2&firstparam=1

I think the move here is to add support for duplicate keys in GET requests, to match the behavior of curl itself.

**Comment by verhovsky** [comment]
I think the difference here is whether they're in the `--data` or in the URL. 

It does respect duplicate keys in GET request though (or I don't understand what you're saying). Having a list for one entry or multiple entries works the same in requests:

```py
>>> resp = requests.get("https://example.com/", params=(('first', ['1', '1']),))
>>> resp.request.url
'https://example.com/?first=1&first=1'
>>> resp = requests.get("https://example.com/", params=(('first', '1'), ('first', '1')))
>>> resp.request.url
'https://example.com/?first=1&first=1'
```

and curlconverter doesn't respect the order for POST requests either, your link is converted to

```py
data = [
  ('firstparam', '1'),
  ('firstparam', '1'),
  ('secondparam', '2'),
]
```

not

```py
data = [
  ('firstparam', '1'),
  ('secondparam', '2'),
  ('firstparam', '1'),
]
```

**Comment by verhovsky** [comment]
I'm going to close this PR in favor of adding "Copy as Python requests" to Chrome directly https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2680281 (still a WIP)

Out of curiosity, I went looking for the source code of where this happens in Chrome, it's this function

https://github.com/ChromeDevTools/devtools-frontend/blob/400dcba55573eee9e36168985616f0c88aa58bec/front_end/network/NetworkLogView.js#L2241-L2370

**Pull request closed without merging**
